spring:
  profiles:
    active: prod
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.uploadPath}
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #    设置上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /www/temp/data
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3307/intelligent_bot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: mysql2023
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 30
    initialSize: 1
    maxWait: 60000
    minIdle: 2
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    validationQuery: select '1'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    port: 6380
    password: redis2023
    database: 1
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    timeout: 100s
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
#配置mybatis-plus 开启日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath:mapper/*.xml
wx:
  mp:
    app-id: wx226b6a31691e9641
    secret: d2dd24c4caa9a0839dfbd96fa6e99fba
    config-storage:
      type: redistemplate
